### ISSUE TITLE
현재 ajax, html연결과 관련한 이슈

### ISSUE THREAD

**Issue by fish1767** [Keitiankor/matchcode#15]
ajax를 활용하여 html파일과 연결후
매치멤버의 이름들을 출력하려는 상황입니다.

현재 ajax로 구현한 버튼을 클릭하여도 연결이 되지않아 
아무런 응답이 없는 상태입니다.

현재 브랜치는 feature/mypage 입니다.

**Comment by Keitiankor** [comment]
해결해서 푸시해드렸습니다.
